# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [2]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]
BMI = np.array(weight) / np.array(height)**2 * 730
print(BMI)



[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [3]:
def buildmatrix(min, max, shape=(3,3), dType='i'):
    arr = np.random.uniform(min, max, shape)
    if dType == 'f':
        print(arr)
    elif dType == 'i':
        arr = arr.astype(np.int64)
        print(arr)

buildmatrix(3,15)
buildmatrix(3,15, (5,11), 'f')


[[ 4 11 10]
 [ 8  8 12]
 [ 4 13  4]]
[[14.2126251  12.39084852  5.95051243 14.12700321 12.08700831  9.70575494
   4.69409184 11.4340409  14.12295736 13.6417856  14.97151839]
 [12.02818047 10.15283282  8.03820483 12.43806113  4.47730138 12.30396431
   4.64735977  8.73749614  6.39073623 11.72779332  5.85876489]
 [ 8.47710809  7.60571669  7.60162798 12.59511281  9.44402155  4.30458586
   9.43011961 12.91260451  3.50933197 11.00514842  9.685571  ]
 [ 8.35087125  9.03317248  5.13085205 11.91354024 13.26365003 10.62906117
   7.6327425   9.60803648 12.19095177  6.9607314   7.85234411]
 [12.13939749  3.87726984  4.01324823  5.94630439  6.73142133  7.59184053
   3.07020566  8.57581226  4.55955071  9.20796354 11.62585538]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [16]:
import csv
import numpy as np

#Test to make sure you have the correct data
def open_txt(filename, d=','):
    #Open CSV -- RedSox hitting.txt
    data = []
    
    with open(filename, encoding='utf-8') as mData:
        info = csv.reader(mData,delimiter=d)
        
        for row in info:
            data.append(row)
    return data

bs2017 = open_txt('files/redsox_2017_hitting.txt')
bs2018 = open_txt('files/redsox_2018_hitting.txt')

print(bs2017[0].index('SLG'))
print(bs2018[0].index('SLG'))
slugs17 = np.array(bs2018)[1:,19].astype(np.float64)
slugs18 = np.array(bs2017)[1:,19].astype(np.float64)
print(slugs17)
print(slugs18)


19
19
[0.279 0.433 0.388 0.522 0.433 0.465 0.403 0.64  0.629 0.411 0.283 0.328
 0.395 0.507 0.311 0.415 0.389 0.261 0.091 0.167]
[0.404 0.443 0.392 0.403 0.482 0.424 0.402 0.459 0.429 0.354 0.387 0.333
 0.539 0.243 0.262 0.354 0.342 0.339 0.328 0.306 0.222 0.2   1.   ]


In [ ]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d=','):
    data = np.genfromtxt(filename,delimiter=d, skip_header = 1, usecols = np.arange(0,28), invalid_raise = False, names = FIELDS, dtype=DATATYPES)
#     Get data with a similar example to class lecture
    return data

bos_17 = load_data('files/redsox_2017_hitting.txt')
bos_18 = load_data('files/redsox_2018_hitting.txt')
